### ISSUE TITLE
NEED UPDATE

### ISSUE THREAD

**Issue by abhishek213-alb** [score-spec/score-helm#18]
I cam to know people are spamming in community asking to star this repo and giving money in exchange can anyone explain

![Screenshot_20230121-192317_Chrome](https://user-images.githubusercontent.com/76660005/213870062-bd040564-7feb-4256-ac85-1946a9c92b8b.jpg)

Attached is the image

**Comment by abhishek213-alb** [comment]
@ghen @rachfop @sayarg 

Please take action

**Comment by sujaya-sys** [comment]
@abhishek213-alb Thank you for reporting this. The form has now been deleted and this issue should hopefully be resolved.

**Comment by abhishek213-alb** [comment]
Hey the form is still open here is the link
https://docs.google.com/forms/d/e/1FAIpQLSe9sEgWp9CkUvx4iGEyckEKDcIL4Ou4nbJ54cv4Dgaj3IiVVA/viewform

**Comment by sujaya-sys** [comment]
Looks like several versions of the form were out there. Should be all clear now. Thanks again!
