### ISSUE TITLE
[docs] Typo in README.md

### ISSUE THREAD

**Issue by Jemeni11** [score-spec/score-helm#19]
A word, **productivity**, was misspelled as **producticity**.

- Go to Readme.md.
- Scroll to the **Score overview** section.
- See error in the first sentence. The sentence:
> Score aims to improve developer producticity and experience by reducing the risk of configurtaion inconsistencies between local and remote environments.

**Comment by sujaya-sys** [comment]
Thanks for pointing this out! I changed "configurtaion" to "configuration" in the score-compose, score-helm and score-humanitec repositories.
